module "lz-vending" {
  source                                            = "Azure/lz-vending/azurerm"
  version                                           = "2.0.0"
  disable_telemetry                                 = var.disable_telemetry
  location                                          = var.location
  role_assignment_enabled                           = var.role_assignment_enabled
  role_assignments                                  = var.role_assignments
  subscription_alias_enabled                        = var.subscription_alias_enabled
  subscription_alias_name                           = var.subscription_alias_name
  subscription_billing_scope                        = var.subscription_billing_scope
  subscription_display_name                         = var.subscription_display_name
  subscription_id                                   = var.subscription_id
  subscription_management_group_association_enabled = var.subscription_management_group_association_enabled
  subscription_management_group_id                  = var.subscription_management_group_id
  subscription_tags                                 = var.subscription_tags
  subscription_workload                             = var.subscription_workload
  virtual_network_enabled                           = var.virtual_network_enabled
  virtual_networks                                  = var.virtual_networks
}
