module "avm-res-oracledatabase-cloudexadatainfrastructure" {
  source                               = "Azure/avm-res-oracledatabase-cloudexadatainfrastructure/azurerm"
  version                              = "0.3.1"
  compute_count                        = var.compute_count
  custom_action_timeout_in_mins        = var.custom_action_timeout_in_mins
  customer_contacts                    = var.customer_contacts
  database_server_type                 = var.database_server_type
  display_name                         = var.display_name
  enable_telemetry                     = var.enable_telemetry
  is_custom_action_timeout_enabled     = var.is_custom_action_timeout_enabled
  location                             = var.location
  maintenance_window_days_of_week      = var.maintenance_window_days_of_week
  maintenance_window_hours_of_day      = var.maintenance_window_hours_of_day
  maintenance_window_leadtime_in_weeks = var.maintenance_window_leadtime_in_weeks
  maintenance_window_months            = var.maintenance_window_months
  maintenance_window_patching_mode     = var.maintenance_window_patching_mode
  maintenance_window_preference        = var.maintenance_window_preference
  maintenance_window_weeks_of_month    = var.maintenance_window_weeks_of_month
  name                                 = var.name
  resource_group_id                    = var.resource_group_id
  role_assignments                     = var.role_assignments
  shape                                = var.shape
  storage_count                        = var.storage_count
  storage_server_type                  = var.storage_server_type
  tags                                 = var.tags
  timeouts                             = var.timeouts
  zone                                 = var.zone
}
