module "aks" {
  source                           = "Azure/aks/azurerm"
  version                          = "4.3.0"
  admin_username                   = var.admin_username
  agents_count                     = var.agents_count
  agents_size                      = var.agents_size
  client_id                        = var.client_id
  client_secret                    = var.client_secret
  enable_azure_policy              = var.enable_azure_policy
  enable_http_application_routing  = var.enable_http_application_routing
  enable_log_analytics_workspace   = var.enable_log_analytics_workspace
  enable_role_based_access_control = var.enable_role_based_access_control
  log_analytics_workspace_sku      = var.log_analytics_workspace_sku
  log_retention_in_days            = var.log_retention_in_days
  os_disk_size_gb                  = var.os_disk_size_gb
  prefix                           = var.prefix
  public_ssh_key                   = var.public_ssh_key
  rbac_aad_admin_group_object_ids  = var.rbac_aad_admin_group_object_ids
  rbac_aad_client_app_id           = var.rbac_aad_client_app_id
  rbac_aad_managed                 = var.rbac_aad_managed
  rbac_aad_server_app_id           = var.rbac_aad_server_app_id
  rbac_aad_server_app_secret       = var.rbac_aad_server_app_secret
  resource_group_name              = var.resource_group_name
  sku_tier                         = var.sku_tier
  tags                             = var.tags
  vnet_subnet_id                   = var.vnet_subnet_id
}
