module "avm-res-app-containerapp" {
  source                                = "Azure/avm-res-app-containerapp/azurerm"
  version                               = "0.9.0"
  auth_configs                          = var.auth_configs
  container_app_environment_resource_id = var.container_app_environment_resource_id
  dapr                                  = var.dapr
  enable_telemetry                      = var.enable_telemetry
  identity_settings                     = var.identity_settings
  ingress                               = var.ingress
  kind                                  = var.kind
  location                              = var.location
  lock                                  = var.lock
  managed_identities                    = var.managed_identities
  max_inactive_revisions                = var.max_inactive_revisions
  name                                  = var.name
  registries                            = var.registries
  resource_group_id                     = var.resource_group_id
  resource_group_name                   = var.resource_group_name
  revision_mode                         = var.revision_mode
  role_assignments                      = var.role_assignments
  runtime                               = var.runtime
  secrets                               = var.secrets
  service                               = var.service
  tags                                  = var.tags
  template                              = var.template
  timeouts                              = var.timeouts
  workload_profile_name                 = var.workload_profile_name
}
