module "avm-res-network-privatednszone" {
  source                = "Azure/avm-res-network-privatednszone/azurerm"
  version               = "0.3.3"
  a_records             = var.a_records
  aaaa_records          = var.aaaa_records
  cname_records         = var.cname_records
  domain_name           = var.domain_name
  enable_telemetry      = var.enable_telemetry
  mx_records            = var.mx_records
  ptr_records           = var.ptr_records
  resource_group_name   = var.resource_group_name
  role_assignments      = var.role_assignments
  soa_record            = var.soa_record
  srv_records           = var.srv_records
  tags                  = var.tags
  timeouts              = var.timeouts
  txt_records           = var.txt_records
  virtual_network_links = var.virtual_network_links
}
