module "avm-ptn-alz" {
  source                             = "Azure/avm-ptn-alz/azurerm"
  version                            = "0.3.1"
  base_archetype                     = var.base_archetype
  default_location                   = var.default_location
  default_log_analytics_workspace_id = var.default_log_analytics_workspace_id
  delays                             = var.delays
  display_name                       = var.display_name
  id                                 = var.id
  parent_id                          = var.parent_id
  policy_assignments_to_add          = var.policy_assignments_to_add
  policy_assignments_to_remove       = var.policy_assignments_to_remove
  policy_definitions_to_add          = var.policy_definitions_to_add
  policy_definitions_to_remove       = var.policy_definitions_to_remove
  policy_set_definitions_to_add      = var.policy_set_definitions_to_add
  policy_set_definitions_to_remove   = var.policy_set_definitions_to_remove
  role_assignments                   = var.role_assignments
  role_definitions_to_add            = var.role_definitions_to_add
  role_definitions_to_remove         = var.role_definitions_to_remove
}
