module "avm-res-containerinstance-containergroup" {
  source                              = "Azure/avm-res-containerinstance-containergroup/azurerm"
  version                             = "0.1.0"
  containers                          = var.containers
  diagnostics_log_analytics           = var.diagnostics_log_analytics
  dns_name_label                      = var.dns_name_label
  dns_name_label_reuse_policy         = var.dns_name_label_reuse_policy
  dns_name_servers                    = var.dns_name_servers
  enable_telemetry                    = var.enable_telemetry
  exposed_ports                       = var.exposed_ports
  image_registry_credential           = var.image_registry_credential
  key_vault_key_id                    = var.key_vault_key_id
  key_vault_user_assigned_identity_id = var.key_vault_user_assigned_identity_id
  liveness_probe                      = var.liveness_probe
  location                            = var.location
  managed_identities                  = var.managed_identities
  name                                = var.name
  os_type                             = var.os_type
  priority                            = var.priority
  private_endpoints                   = var.private_endpoints
  readiness_probe                     = var.readiness_probe
  resource_group_name                 = var.resource_group_name
  restart_policy                      = var.restart_policy
  role_assignments                    = var.role_assignments
  subnet_ids                          = var.subnet_ids
  tags                                = var.tags
  zones                               = var.zones
}
