module "avm-res-storage-storageaccount" {
  source                                    = "Azure/avm-res-storage-storageaccount/azurerm"
  version                                   = "0.8.1"
  application_security_group_resource_ids   = var.application_security_group_resource_ids
  dns_zone_group_resource_type              = var.dns_zone_group_resource_type
  edge_zone                                 = var.edge_zone
  ip_configurations                         = var.ip_configurations
  location                                  = var.location
  lock                                      = var.lock
  lock_resource_type                        = var.lock_resource_type
  manage_dns_zone_group                     = var.manage_dns_zone_group
  name                                      = var.name
  network_interface_name                    = var.network_interface_name
  parent_id                                 = var.parent_id
  private_connection_resource_id            = var.private_connection_resource_id
  private_dns_zone_group_name               = var.private_dns_zone_group_name
  private_dns_zone_resource_ids             = var.private_dns_zone_resource_ids
  private_service_connection_name           = var.private_service_connection_name
  resource_type                             = var.resource_type
  retry                                     = var.retry
  role_assignment_definition_lookup_enabled = var.role_assignment_definition_lookup_enabled
  role_assignments                          = var.role_assignments
  subnet_resource_id                        = var.subnet_resource_id
  subresource_name                          = var.subresource_name
  tags                                      = var.tags
  timeouts                                  = var.timeouts
  tracing_tags_header                       = var.tracing_tags_header
}
