module "avm-ptn-network-private-link-private-dns-zones" {
  source                                         = "Azure/avm-ptn-network-private-link-private-dns-zones/azurerm"
  version                                        = "0.21.0"
  enable_telemetry                               = var.enable_telemetry
  location                                       = var.location
  lock                                           = var.lock
  parent_id                                      = var.parent_id
  private_link_excluded_zones                    = var.private_link_excluded_zones
  private_link_private_dns_zones                 = var.private_link_private_dns_zones
  private_link_private_dns_zones_additional      = var.private_link_private_dns_zones_additional
  private_link_private_dns_zones_regex_filter    = var.private_link_private_dns_zones_regex_filter
  resource_group_role_assignments                = var.resource_group_role_assignments
  tags                                           = var.tags
  timeouts                                       = var.timeouts
  virtual_network_link_defaults                  = var.virtual_network_link_defaults
  virtual_network_link_defaults_overrides        = var.virtual_network_link_defaults_overrides
  virtual_network_link_name_template             = var.virtual_network_link_name_template
  virtual_network_link_overrides                 = var.virtual_network_link_overrides
  virtual_network_link_per_zone                  = var.virtual_network_link_per_zone
  virtual_network_link_resolution_policy_default = var.virtual_network_link_resolution_policy_default
}
