module "avm-res-network-privateendpoint" {
  source                                     = "Azure/avm-res-network-privateendpoint/azurerm"
  version                                    = "0.1.0"
  application_security_group_association_ids = var.application_security_group_association_ids
  enable_telemetry                           = var.enable_telemetry
  ip_configurations                          = var.ip_configurations
  location                                   = var.location
  lock                                       = var.lock
  name                                       = var.name
  network_interface_name                     = var.network_interface_name
  private_connection_resource_id             = var.private_connection_resource_id
  private_dns_zone_group_name                = var.private_dns_zone_group_name
  private_dns_zone_resource_ids              = var.private_dns_zone_resource_ids
  private_service_connection_name            = var.private_service_connection_name
  resource_group_name                        = var.resource_group_name
  role_assignments                           = var.role_assignments
  subnet_resource_id                         = var.subnet_resource_id
  subresource_names                          = var.subresource_names
  tags                                       = var.tags
}
