module "avm-ptn-aks-dev" {
  source                                      = "Azure/avm-ptn-aks-dev/azurerm"
  version                                     = "0.3.0"
  agents_tags                                 = var.agents_tags
  container_registry_name                     = var.container_registry_name
  enable_telemetry                            = var.enable_telemetry
  kubernetes_version                          = var.kubernetes_version
  location                                    = var.location
  lock                                        = var.lock
  name                                        = var.name
  orchestrator_version                        = var.orchestrator_version
  rbac_aad_admin_group_object_ids             = var.rbac_aad_admin_group_object_ids
  rbac_aad_azure_rbac_enabled                 = var.rbac_aad_azure_rbac_enabled
  rbac_aad_tenant_id                          = var.rbac_aad_tenant_id
  resource_group_name                         = var.resource_group_name
  tags                                        = var.tags
  user_assigned_identity_name                 = var.user_assigned_identity_name
  user_assigned_managed_identity_resource_ids = var.user_assigned_managed_identity_resource_ids
  vm_size                                     = var.vm_size
}
