module "avm-ptn-azuremonitorwindowsagent" {
  source                                                = "Azure/avm-ptn-azuremonitorwindowsagent/azurerm"
  version                                               = "0.3.0"
  arc_setting_id                                        = var.arc_setting_id
  azurerm_monitor_data_collection_rule_association_name = var.azurerm_monitor_data_collection_rule_association_name
  cmk_for_query_forced                                  = var.cmk_for_query_forced
  counter_specifiers                                    = var.counter_specifiers
  create_data_collection_resources                      = var.create_data_collection_resources
  data_collection_endpoint_name                         = var.data_collection_endpoint_name
  data_collection_endpoint_tags                         = var.data_collection_endpoint_tags
  data_collection_rule_destination_id                   = var.data_collection_rule_destination_id
  data_collection_rule_name                             = var.data_collection_rule_name
  data_collection_rule_resource_id                      = var.data_collection_rule_resource_id
  data_collection_rule_tags                             = var.data_collection_rule_tags
  enable_telemetry                                      = var.enable_telemetry
  immediate_data_purge_on_30_days_enabled               = var.immediate_data_purge_on_30_days_enabled
  lock                                                  = var.lock
  name                                                  = var.name
  resource_group_name                                   = var.resource_group_name
  retention_in_days                                     = var.retention_in_days
  role_assignments                                      = var.role_assignments
  server_names                                          = var.server_names
  sku                                                   = var.sku
  workspace_name                                        = var.workspace_name
  workspace_tags                                        = var.workspace_tags
  x_path_queries                                        = var.x_path_queries
}
