module "avm-res-machinelearningservices-workspace" {
  source                    = "Azure/avm-res-machinelearningservices-workspace/azurerm"
  version                   = "0.2.1"
  ai_studio_hub_id          = var.ai_studio_hub_id
  aiservices                = var.aiservices
  application_insights      = var.application_insights
  container_registry        = var.container_registry
  create_compute_instance   = var.create_compute_instance
  customer_managed_key      = var.customer_managed_key
  enable_telemetry          = var.enable_telemetry
  hbi_workspace             = var.hbi_workspace
  is_private                = var.is_private
  key_vault                 = var.key_vault
  kind                      = var.kind
  location                  = var.location
  lock                      = var.lock
  log_analytics_workspace   = var.log_analytics_workspace
  name                      = var.name
  private_endpoints         = var.private_endpoints
  resource_group_name       = var.resource_group_name
  role_assignments          = var.role_assignments
  storage_account           = var.storage_account
  tags                      = var.tags
  vnet                      = var.vnet
  workspace_managed_network = var.workspace_managed_network
}
