output "resource" {
  value       = module.avm-res-compute-virtualmachine.resource
  description = "This is a repeat of the sku value to satisfy the AVM spec requirement for a resource output."
}

output "resource_id" {
  value       = module.avm-res-compute-virtualmachine.resource_id
  description = "This is a repeat of the sku value to satisfy the AVM spec requirement for a resource_id output."
}

output "sku" {
  value       = module.avm-res-compute-virtualmachine.sku
  description = "The sku value generated by the sku selector tool"
}
