module "avm-res-edge-site" {
  source                = "Azure/avm-res-edge-site/azurerm"
  version               = "0.1.3"
  address_resource_name = var.address_resource_name
  city                  = var.city
  company_name          = var.company_name
  contact_name          = var.contact_name
  country               = var.country
  customer_managed_key  = var.customer_managed_key
  email_list            = var.email_list
  enable_telemetry      = var.enable_telemetry
  location              = var.location
  lock                  = var.lock
  mobile                = var.mobile
  phone                 = var.phone
  phone_extension       = var.phone_extension
  postal_code           = var.postal_code
  resource_group_id     = var.resource_group_id
  role_assignments      = var.role_assignments
  site_display_name     = var.site_display_name
  site_resource_name    = var.site_resource_name
  state_or_province     = var.state_or_province
  street_address_1      = var.street_address_1
  street_address_2      = var.street_address_2
  street_address_3      = var.street_address_3
  tags                  = var.tags
  zip_extended_code     = var.zip_extended_code
}
