module "avm-res-web-serverfarm" {
  source                          = "Azure/avm-res-web-serverfarm/azurerm"
  version                         = "0.8.0"
  app_service_environment_id      = var.app_service_environment_id
  enable_telemetry                = var.enable_telemetry
  location                        = var.location
  lock                            = var.lock
  maximum_elastic_worker_count    = var.maximum_elastic_worker_count
  name                            = var.name
  os_type                         = var.os_type
  per_site_scaling_enabled        = var.per_site_scaling_enabled
  premium_plan_auto_scale_enabled = var.premium_plan_auto_scale_enabled
  resource_group_name             = var.resource_group_name
  role_assignments                = var.role_assignments
  sku_name                        = var.sku_name
  tags                            = var.tags
  worker_count                    = var.worker_count
  zone_balancing_enabled          = var.zone_balancing_enabled
}
