module "avm-res-hybridcontainerservice-provisionedclusterinstance" {
  source                          = "Azure/avm-res-hybridcontainerservice-provisionedclusterinstance/azurerm"
  version                         = "0.1.0"
  agent_pool_profiles             = var.agent_pool_profiles
  control_plane_count             = var.control_plane_count
  control_plane_ip                = var.control_plane_ip
  control_plane_vm_size           = var.control_plane_vm_size
  custom_location_id              = var.custom_location_id
  customer_managed_key            = var.customer_managed_key
  enable_azure_rbac               = var.enable_azure_rbac
  enable_telemetry                = var.enable_telemetry
  is_exported                     = var.is_exported
  kubernetes_version              = var.kubernetes_version
  location                        = var.location
  lock                            = var.lock
  logical_network_id              = var.logical_network_id
  managed_identities              = var.managed_identities
  name                            = var.name
  pod_cidr                        = var.pod_cidr
  rbac_admin_group_object_ids     = var.rbac_admin_group_object_ids
  resource_group_name             = var.resource_group_name
  role_assignments                = var.role_assignments
  ssh_key_vault_id                = var.ssh_key_vault_id
  ssh_private_key_pem_secret_name = var.ssh_private_key_pem_secret_name
  ssh_public_key                  = var.ssh_public_key
  ssh_public_key_secret_name      = var.ssh_public_key_secret_name
  tags                            = var.tags
}
